### ISSUE TITLE
Question: What Firefox Theme is used on the Screenshots?

### ISSUE THREAD

**Issue by AtjonTV** [rajshekhar26/startpage#5]
Hello! I just got this repo recommended by Github and I wonder and just have to know what Theme is used in the Screenshots?

It looks so fancy and I want it (even though I am a Brave user)

**Comment by rajshekhar26** [comment]
I did not install any theme. I created [userChrome.css](https://github.com/rajshekhar26/startpage/blob/master/chrome/userChrome.css) and put my styles in it, you can do it in Firefox.

**Comment by rajshekhar26** [comment]
> Hello! I just got this repo recommended by Github and I wonder and just have to know what Theme is used in the Screenshots?
> 
> It looks so fancy and I want it (even though I am a Brave user)

I created it myself by putting styles in useChrome.css. It only works in firefox, you can find it [here](https://github.com/rajshekhar26/FaintFox)
